import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const postSchema = ({ image }: any) =>
	z.object({
		// ── Existing fields — unchanged ──
		title: z.string(),
		description: z.string(),
		pubDate: z.coerce.date(),
		updatedDate: z.coerce.date().optional(),
		draft: z.boolean().optional(),
		heroImage: z.optional(image()),

		// ── ELI Criticality Scale ──
		// Agent-suggested at draft time. Jason confirms at Gate 1.
		// L0 = Normal/Educational  L1 = Advisory  L2 = Warning  L3 = Critical
		criticality: z.enum(['L0', 'L1', 'L2', 'L3']).optional(),

		// ── Conclusion State ──
		// Drives takeaway block badge color in article layout.
		// safe = green  hazard = red  neutral = gray
		conclusion_state: z.enum(['safe', 'hazard', 'neutral']).optional(),

		// ── Agent / Editor flags ──
		// agent_suggested: true when PRODUCE/TRIAGE set the fields above
		// editor_confirmed: Jason flips to true at Gate 1 before publish
		agent_suggested: z.boolean().optional(),
		editor_confirmed: z.boolean().optional(),

		// ── SEO fields ──
		// Generated by PRODUCE agent SEO block. Reviewed at Gate 1.
		seoTitle: z.string().optional(),
		metaDescription: z.string().optional(),
		primaryKeyword: z.string().optional(),
	});

const incidents = defineCollection({
	loader: glob({ base: './src/content/incidents', pattern: '**/*.{md,mdx}' }),
	schema: postSchema,
});

const safetyTopics = defineCollection({
	loader: glob({ base: './src/content/safety-topics', pattern: '**/*.{md,mdx}' }),
	schema: postSchema,
});

const safetyNews = defineCollection({
	loader: glob({ base: './src/content/safety-news', pattern: '**/*.{md,mdx}' }),
	schema: postSchema,
});

export const collections = { incidents, 'safety-topics': safetyTopics, 'safety-news': safetyNews };