name: Daily Netlify Build

on:
  schedule:
    # Runs at 3:00 AM Eastern Time (07:00 UTC) every day to prevent race conditions with MailerLite.
    # MailerLite RSS Campaign is set to send at 5:30 AM Eastern.
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab if you want to force a build

jobs:
  daily-build:
    name: Trigger Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Ping Netlify Build Hook
        run: curl -X POST -d {} ${{ secrets.NETLIFY_ELI_BUILD_HOOK }}
